language: node_js
node_js:
  - "4.1"
before_script:
  - sudo apt-get update
  - sudo apt-get install --assume-yes fonts-liberation libappindicator1
  - wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i /tmp/chrome.deb
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run codecov
