language: node_js
node_js:
  - 6
os:
  - linux
  - osx
before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CHROME_BIN=chromium-browser ; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start ; fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew cask install google-chrome; fi
  - sleep 3 # give xvfb some time to start
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - node_modules
addons:
  firefox: latest-esr
