language: node_js
dist: trusty # for chrome
sudo: required # for chrome
node_js:
  - 8
os:
  - linux
before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export CHROME_BIN=google-chrome ; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start ; fi
  - sleep 3 # give xvfb some time to start
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - node_modules
addons:
  firefox: latest-esr
  chrome: stable
